services:
  db:
    image: mysql:8.0
    container_name: mysql-cs232
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: cs232db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./sql/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      timeout: 5s
      retries: 10
      interval: 5s

  backend:
    build: .
    container_name: backend-cs232-container
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: cs232db
      DB_USER: root
      DB_PASSWORD: 1234

volumes:
  mysql_data: