import type { Metadata } from "next";
import { Geist, Geist_Mono, Jua, Mali } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const jua = Jua({
  subsets: ["latin"],
  weight: "400",
});

const mali = Mali({
  subsets: ["thai"],
  weight: ["400", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
       <body
        className={`${jua.className} flex`}
        style={{ fontFamily: `${jua.style.fontFamily}, ${mali.style.fontFamily}` }}
      >
        <Sidebar />
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
